<section class="loan-section">
    <div class="loan-warp">
        <div class="container">
            <div class="section-title text-white">
                <h2>Newsletter o wydarzeniach w Trójmieście</h2>
            </div>
            <form class="loan-form">

                <input type="text" placeholder="Podaj maila do Newslettera">
                <button class="site-btn">Zapisz</button>
            </form>
        </div>
    </div>
</section>